# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka1:19092
#  schemaRegistry:
#    enabled: true
#    urls: [http://localhost:8082] # Url with scheme is required, e.g. ["http://localhost:8081"]
